name: CD(continuous deployment)

on:
  pull_request: 
    branches: 
      - develop
      - staging
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest    
    steps:

      - uses: actions/checkout@v2
    
      - name: Setting Node.js
        uses: actions/setup-node@v2

      - name: Run tests
        run: npm install && npm run test

      - name: Notify CI process
        if: always()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: CI executed ${{ job.status }}.
